### ISSUE TITLE
ajouter une ligne de texte affichée par Bonjour, puis lancer dans le codespace

### ISSUE THREAD

**Issue by jycolinLH** [jycolinLH/testWF#5]
permettra de tester la réutiiisation d'un codespace de la branche main, dans une sous-branche

**Comment by jycolinFR** [comment]
OK il fallait bien considérer le codespace lancé comme une machine locale indépendante, qui aurait github.com comme un dépôt distant. Donc une fois satisfait de ce qu'on a écrit dans le codespace,

- faire un "git add ..." d'abord si on a ajouté de nouveaux fichiers dans le codespace
- sinon faire un simple "git commit -a" dans le codespace
- on a un commit local au codespace
- puis faire "git push"  pour pousser le tout vers le dépôt distant qu'est GitHub.com
- on peut enfin arrêter le codespace, avec par exemple "gh codespace stop"
